### ISSUE TITLE
ev3-print3rbot-master

### ISSUE THREAD

**Issue by arbybo** [cavenel/ev3-print3rbot#21]
help 
La versione [ev3dev-jessie-ev3-generic-2017-02-11]

robot @ ev3dev: ~ $ python3 writer.py 
Traceback (ultima chiamata ultima): 
File "writer.py", riga 481, nella cartella 
principale () 
"writer.py", riga 472, in principale 
wri = Writer (calibrate = True) 
File "writer.py", riga 79, in init
self.calibrate () 
File "writer.py", riga 111, nella calibrazione 
se (self.touch_A.value ()): 
File "/ usr / lib / python3 "/ usr" 
, valore = self.get_attr_int (valore self._value [n], 'valore' + str (n)) 
" /src/packages/ev3dev/core.py", linea 1712, valore self._value [n] /lib/python3/dist-packages/ev3dev/core.py ", riga 213, nell'attributo get_attr_int 
, value = self._get_attribute (attributo, nome)
File "/usr/lib/python3/dist-packages/ev3dev/core.py", riga 197, in ritiro _get_attribute 
Eccezione ('Dispositivo non è connesso') 
Eccezione: il dispositivo non è connesso

**Comment by cavenel** [comment]
I guess your console is this one (without the Spanish translation):
```
robot@ev3dev:~$ python3 writer.py
Traceback (most recent call last):
File "writer.py", line 481, in 
main()
File "writer.py", line 472, in main
wri = Writer(calibrate = True)
File "writer.py", line 79, in init
self.calibrate()
File "writer.py", line 111, in calibrate
if (self.touch_A.value()):
File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 1712, in value
self._value[n], value = self.get_attr_int(self._value[n], 'value'+str(n))
File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 213, in get_attr_int
attribute, value = self._get_attribute(attribute, name)
File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 197, in _get_attribute
raise Exception('Device is not connected')
Exception: Device is not connected
```

I would say check that you have a touch sensor connected to INPUT_3.
