### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Muneera-Salah** [cavenel/ev3-print3rbot#22]
![screenshot 2017-10-21 20 52 43](https://user-images.githubusercontent.com/3780724/32888501-7f2c697c-cad8-11e7-8497-3619414d6063.png)
Hi Sir,,
 I get these error when I  run  writer.py file

robot@ev3dev:~/ev3-print3rbot$ ./writer.py
Traceback (most recent call last):
  File "./writer.py", line 481, in <module>
    main()
  File "./writer.py", line 472, in main
    wri = Writer(calibrate = True)
  File "./writer.py", line 79, in __init__
    self.calibrate()
  File "./writer.py", line 111, in calibrate
    if (self.touch_A.value()):
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 1758, in value
    self._value[n], value = self.get_attr_int(self._value[n], 'value'+str(n))
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 214, in get_attr_int
    attribute, value = self._get_attribute(attribute, name)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 198, in _get_attribute
    raise Exception('Device is not connected')
Exception: Device is not connected

**Comment by Brad750** [comment]
I have this same error.  Did you ever correct this?
