### ISSUE TITLE
I Cant runing

### ISSUE THREAD

**Issue by mohammed666** [cavenel/ev3-print3rbot#24]
help 

robot@ev3dev:~/ev3-print3rbot$ sudo python3 writer.py
[sudo] password for robot:
Traceback (most recent call last):
  File "writer.py", line 481, in <module>
    main()
  File "writer.py", line 474, in main
    wri.draw_image(image_file = 'images/test.svg',max_speed=35)
  File "writer.py", line 438, in draw_image
    list_points = self.fit_path (self.read_svg (image_file))
  File "writer.py", line 356, in read_svg
    path = [s.attributes['d'].value for s in itemlist]
  File "writer.py", line 356, in <listcomp>
    path = [s.attributes['d'].value for s in itemlist]
  File "writer.py", line 353, in <lambda>
    itemlist = filter(lambda x: x.attributes['id'].value != "borders", itemlist)
  File "/usr/lib/python3.4/xml/dom/minidom.py", line 555, in __getitem__
    return self._attrs[attname_or_tuple]
KeyError: 'id'
robot@ev3dev:~/ev3-print3rbot$

**Comment by mohammed666** [comment]
plse 

help me

i try ran the project

 File "writer.py", line 481, in <module>
    main()
  File "writer.py", line 474, in main
    wri.draw_image(image_file = 'images/test.svg',max_speed=35)
  File "writer.py", line 439, in draw_image
    self.follow_path(list_points, max_speed=max_speed)
  File "writer.py", line 311, in follow_path
    return self.follow_path (list_points, max_speed)
  File "writer.py", line 311, in follow_path
    return self.follow_path (list_points, max_speed)
  File "writer.py", line 326, in follow_path
    self.goto_point (x,y,brake,lastx, lasty, max_speed=max_speed)
  File "writer.py", line 291, in goto_point
    while (self.set_speed_to_coordinates (x,y,max_speed_,initx,inity,brake)):
  File "writer.py", line 264, in set_speed_to_coordinates
    next_posB, next_posA = Writer.coordinates_to_motorpos (nextx, nexty)
  File "writer.py", line 212, in coordinates_to_motorpos
    (alpha, beta) = Writer.coordinates_to_angles (x, y)
TypeError: 'NoneType' object is not iterable
